name: Build

on:
  workflow_call:
    outputs:
      has_changed_packages:
        description: Whether there are any changed packages in monorepo.
        value: ${{ jobs.build.outputs.has_changed_packages }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      has_changed_packages: ${{ steps.check-changed-packages.outputs.has_changed_packages }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run setup
        uses: ./.github/actions/setup

      - id: check-changed-packages
        uses: ./.github/actions/check-changed-packages

      - id: resolve-since-flag
        if: ${{ steps.check-changed-packages.outputs.has_changed_packages == 'true' }}
        uses: ./.github/actions/resolve-lerna-since-flag

      - name: Build
        if: ${{ steps.check-changed-packages.outputs.has_changed_packages == 'true' }}
        shell: bash
        env:
          SINCE_FLAG: ${{ steps.resolve-since-flag.outputs.since_flag }}
        run: npx lerna run build $SINCE_FLAG --include-dependencies
